### ISSUE TITLE
GeometryFactory's createMultiPoint creates Geometries where type is Coordinate

### ISSUE THREAD

**Issue by jericks** [bjornharrtell/jsts#251]
When I create a MultiPoint from WKT, the individual Geometries are Points.  But when I create a MultiPoint using a GeometryFactory, the individual Geometries are Coordinates, so a call to toText() fails with this error:

TypeError: this.geometries[t].isEmpty is not a function
    at MultiPoint.extend.isEmpty (/Users/jericks/Projects/jsts-cli/node_modules/jsts/dist/jsts.min.js:11:19547)
    at WKTParser.extend.extractGeometry (/Users/jericks/Projects/jsts-cli/node_modules/jsts/dist/jsts.min.js:12:24901)
    at WKTParser.extend.write (/Users/jericks/Projects/jsts-cli/node_modules/jsts/dist/jsts.min.js:12:24751)
    at WKTWriter.extend.write (/Users/jericks/Projects/jsts-cli/node_modules/jsts/dist/jsts.min.js:12:28632)

Here is a short script illustrating the problem:

var jsts = require('jsts');

var reader = new jsts.io.WKTReader();
var mp = reader.read('MULTIPOINT (1 1, 2 2, 3 3)');

for(var i = 0; i<mp.getNumGeometries(); i++) {
  console.log(mp.getGeometryN(i));
}
console.log(mp.toText());

mp = mp.getFactory().createMultiPoint(mp.getCoordinates());
for(var i = 0; i<mp.getNumGeometries(); i++) {
  console.log(mp.getGeometryN(i));
}
console.log(mp.toText()); // Error thrown here

I am using version 1.0.3.

Thanks!
Jared

**Comment by bjornharrtell** [comment]
The original API in JTS for createMultiPoint is overloaded so it can accept both Coordinate[] and Point[] and this is one of the rare cases where the JavaScript conversion cannot resolve the overload, because the type information of the array parameter is lost. Perhaps an improved conversion can fix this in the future, meanwhile it should work if you use createMultiPoint with a Point[] argument instead of Coordinate[].

**Comment by bjornharrtell** [comment]
Others have been troubled by this particular case so I've added it to a caveats section in https://github.com/bjornharrtell/jsts/blob/master/README.md.
