### ISSUE TITLE
Overlay operations fails for specific geometries

### ISSUE THREAD

**Issue by evansiroky** [bjornharrtell/jsts#273]
See following code:

```javascript
var jsts = require('jsts')

var geoJsonReader = new jsts.io.GeoJSONReader()

var _a = geoJsonReader.read(JSON.stringify({type:"MultiPolygon",coordinates:[[[[-98.66785844242092,26.235876466237066],[-101.36626498980094,48.9994722],[-98.6185317,26.2500014],[-98.61852,26.25039],[-98.66785844242092,26.235876466237066]]]]})),
  _b = geoJsonReader.read(JSON.stringify({type:"MultiPolygon",coordinates:[[[[-92.06236267089844,48.351318359375],[-101.36641693115234,48.99555206298828],[-101.36410522460938,49.05519485473633],[-101.35955047607422,49.17183303833008],[-92.06236267089844,48.351318359375]]]]}))

var result = _a.difference(_b)
```

**Comment by bjornharrtell** [comment]
This currently fail with `TypeError: this.seg.p1.equals2D is not a function at LineStringSnapper.findSegmentIndexToSnap` because `SnapOverlayOp` does not work as expected.

However, SnapOverlayOp is only used if needed because of robustness issues and in this case it cannot produce a result. The correct failure message should be `TopologyException: found non-noded intersection between LINESTRING ( -101.36578623196883 48.99550839195418, -98.6185317 26.2500014 ) and LINESTRING ( -98.61852 26.25039, -98.66785844242092 26.235876466237066 ) [ (-98.61857662416273, 26.25037334327844, NaN) ]`.

**Comment by bjornharrtell** [comment]
I noted that the `_a` geometry is not valid which might be the cause of robustness issues.

**Comment by evansiroky** [comment]
I initially trimmed down the geojson to the smallest possible size that would produce the same error.  Looks like that produced invalid geojson.  I have uploaded the full dataset that produced the error here:  http://evansiroky.com/temp/jsts_273/ and made sure the json was valid at http://geojsonlint.com/

**Comment by bjornharrtell** [comment]
Thanks. Would it be ok to zip those files and attach them here so to not rely on an external host?

About "valid" I did not mean the JSON, I mean the geometry itself not conforming to the OGC definition of valid which is a requirement for the overlay operation to work as expected. The most common cause is self-intersections.

**Comment by evansiroky** [comment]
Test file is uploaded in [test.zip](https://github.com/bjornharrtell/jsts/files/328205/test.zip).  

And yes, I meant to say valid GeoJSON.  The curtailed JSON for geometry A does self-intersect.

**Comment by bjornharrtell** [comment]
Ok, so what I'm saying is that the difference operation assumes valid geometry, if not it will most probably fail. In some cases even valid geometry can fail because of precision issues.

The error message is misleading and as I wrote before indicates a bug in JSTS, but even if I can correct it the result will probably still be an error but a TopologyException.

**Comment by bjornharrtell** [comment]
After https://github.com/bjornharrtell/jsts/commit/4b0380caacc9f891b950ea3999b8d5063142fa1d I now get the expected error:

`TopologyException: found non-noded intersection between LINESTRING ( -101.36578623196883 48.99550839195418, -98.6185317 26.2500014 ) and LINESTRING ( -98.61852 26.25039, -98.66785844242092 26.235876466237066 ) [ (-98.61857662416273, 26.25037334327844, undefined) ]`

**Comment by evansiroky** [comment]
Thanks a bunch for working on this!  Do you have any recommendations on how to avoid the TopologyException error?  I submitted a pull request (#277) to expose the PrecisionModel so I can follow the recommendations given [here](http://tsusiatsoftware.net/jts/jts-faq/jts-faq.html#D9).  Am I on the right track with that?

**Comment by bjornharrtell** [comment]
Yes, you need to simplify the geometry and for that you need to specify a PrecisionModel.
