### ISSUE TITLE
GeometryPrecisionReducer.reduce throws unexpected error

### ISSUE THREAD

**Issue by evansiroky** [bjornharrtell/jsts#279]
When attempting to reduce the precision of a geometry using the `reduce` method of `GeometryPrecisionReducer` on specific geometries, the error `TypeError: Cannot read property 'interfaces_' of null` is thrown. See attached test case:  [test.zip](https://github.com/bjornharrtell/jsts/files/350710/test.zip)

**Comment by bjornharrtell** [comment]
Thanks for reporting. Want to get fix fixed when possible. Hopefully no more follow up bugs after that. :)

**Comment by bjornharrtell** [comment]
Bug is triggered by geometry collapses i.e polygons turning into points because they are too small. `GeometryPrecisionReducer` should take care of that but the code path taken ends up at
https://github.com/bjornharrtell/jsts/blob/1.2.0/src/org/locationtech/jts/precision/PrecisionReducerCoordinateOperation.js#L34 where the returned value is `null` which in original JTS would create an empty geometry but JSTS requires call to parameter-less constructor instead. Unfortuneately, after fixing this more issues remain ending up at https://github.com/bjornharrtell/jsts/blob/1.2.0/src/org/locationtech/jts/geom/GeometryFactory.js#L168 where JTS translation seem to have gone wrong.

Short story, fixing `GeometryPrecisionReducer` seems non trivial.

**Comment by bjornharrtell** [comment]
Found that `createGeometry` is only used at `https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/precision/GeometryPrecisionReducer.js#L24` and can be worked around and/or removed. Still needs more for a proper fix.

**Comment by evansiroky** [comment]
Thanks for all your work!  A quick comment is that I noticed that it is best to specify a multiple of 10 for the scale factor of Precision Model (see [jts docs](http://tsusiatsoftware.net/jts/javadoc/com/vividsolutions/jts/geom/PrecisionModel.html)).  Also after manually reducing the geometries I manually created and using your experimental fix I've been able to run my program without errors!
