### ISSUE TITLE
Publish TypeScript typings

### ISSUE THREAD

**Issue by danvk** [bjornharrtell/jsts#285]
There are [some type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/39c221338d56e953b745bfdd761f8c594d8f92da/jsts/jsts.d.ts) available on DefinitelyTyped, but they're woefully incomplete (they only cover `jsts.geom` and parts of `jsts.io`). An official set of type definitions would be a big usability win for TypeScript users and a documentation win for everyone.

**Comment by bjornharrtell** [comment]
An interesting project would be to translate the upstream source directly to TypeScript.

**Comment by Montago** [comment]
So... any news on TypeScript ?

the TypeDef available on DefinitlyTyped are incomplete :-(

**Comment by bjornharrtell** [comment]
I currently have no personal interest in bindings, but I would love to target TypeScript directly using similar code transformation as I did for ES5. However it will require non-trivial efforts which I as of yet has not planned.

**Comment by HarelM** [comment]
Hi,
I'm currently using turf in my frontend and NTS in my backend.
I'm failing to find a good way to project a point onto a line segment in turf in order to find the closest point on a line (I know I can write this code, but I prefer to use a tested library instead...), and since I'm used to working with NTS (.net port of JTS) I thought I might switch to use this library.
However, I was wondering what's the status of typescript typings and the ability to import only what I need (linked issue) to make sure the production code stays small.
Thanks ahead! If I can help in the effort of migrating this library to TypeScript let me know...

**Comment by AnderssonPeter** [comment]
@HareIM doesn't https://turfjs.org/docs/#nearestPointOnLine do what you are asking for?

**Comment by AnderssonPeter** [comment]
Yes typescript is a life saver, sadly jsts is unusable in a typescript environment without correct typings.

**Comment by bjornharrtell** [comment]
It's definitely doable, but I still have no pressing need myself.

**Comment by PauloSSAragao** [comment]
> An interesting project would be to translate the upstream source directly to TypeScript.

Hi Bjorn, 
a lot of complex js libraries instead of migrate to typescript, they use jsdoc to generate the typescript types.
For instance, for cesiumjs library, they have adopted this approach: https://cesium.com/blog/2020/06/01/cesiumjs-tsd/

Here is a guide how to generate: https://dev.to/jor/jsdoc-to-typescript-declaration-19fg

In the cesiumjs code you can check the source code with the jsdoc tags: https://github.com/CesiumGS/cesium

**Comment by bjornharrtell** [comment]
@PauloSSAragao that implies correct jsdoc transpiled from JavaDoc, which I believe is about as difficult to transpile to as TypeScript and less verifiable.

**Comment by simonseyock** [comment]
@bjornharrtell I would find it interesting to investigate what would be needed in order to automatically generate typescript code from the java jts code. Would this be appreciated for this project? If so I would read into the bundler code and see how it could be modified to generate typescript as I don't see any library that could do this natively.

**Comment by bjornharrtell** [comment]
@simonseyock JSTS was made by transpiling patched Java upstream code (JTS) to JavaScript with use of my own custom transpiler which can be found at https://github.com/bjornharrtell/java2estree made in Scala. It's pretty hacky stuff, so be warned. But it should be possible to hack it some more to output TypeScript instead. But it is no trivial task and requires Scala knowledge. I still have some interest in this and would welcome efforts.. my own priorities do not allow a large investment at this time.

**Comment by simonseyock** [comment]
Ok, I might have some time at hands in the near future and will start looking into this. I do not know Scala, but I worked with functional programming languages before and also other languages on the java VM. So it might be interesting to try it out..

**Comment by bjornharrtell** [comment]
I've had some fun modernizing https://github.com/bjornharrtell/java2estree a bit.. and realized there is a problem with regard to this issue. The way java2estree works is by generating AST in estree format which is then transformed to JavaScript using a third party tool called astring. For TypeScript this will be have to be replaced by something equivalent and I'm not even sure that exists.

**Comment by Montago** [comment]
You dont need to translate the whole library, only made the types documents that describe objects, return types and methods ..etc..

Given that Java is type strong, you only need to scratch the surface.. 

Creating a library scraper shouldnt be too hard a challenge for a seasoned programmer

**Comment by bjornharrtell** [comment]
Hmm looks like there is some kind of more or less official TypeScript AST and the TypeScript compiler can turn that into code (see https://stackoverflow.com/questions/65213952/how-to-generate-code-from-ast-typescript-parser). Looks pretty promising actually!

**Comment by bjornharrtell** [comment]
Food for thought, https://github.com/typescript-eslint/typescript-eslint/discussions/7228.

**Comment by simonseyock** [comment]
If the typescript compiler can be used, that is definitely the way to go.

**Comment by bjornharrtell** [comment]
Some time ago I learned tsc can generate types for plain JS. It will of course not be as good types as if the source is  TS but hopefully better than nothing, so with https://github.com/bjornharrtell/jsts/commit/13cc0b939af5a1f9ff860dcebf8f075ce0294bdd and latest release such types are included.
