### ISSUE TITLE
Exports java objects (like ArrayList) for allowing its usage

### ISSUE THREAD

**Issue by rulyotano** [bjornharrtell/jsts#299]
For instance, the `jsts.geom.GeometryFactory.buildGeometry()` needs a enumerable java object, but it isn't exported in the library. For this case, I have done a custom project's branch in https://github.com/rulyotano/jsts-with-exports But I think it also should be done in this project. 

`var geoList = new jsts.java.util.ArrayList();`
`...`
`var unionGeometry = (new jsts.geom.GeometryFactory()).buildGeometry(geoList)`

**Comment by bjornharrtell** [comment]
I have no test cases for `buildGeometry` and the internal java.util ports are undocumented, which is why I have not exported them and would like to avoid it. If it's only for the sake of `buildGeometry` perhaps there is another way to support that particular case I'll have to think about it until next release.
