### ISSUE TITLE
LinearRing contructor should consider Coordinate[]

### ISSUE THREAD

**Issue by peterza** [bjornharrtell/jsts#300]
I think there is an error in the contructor of a LinearRing.
Shouldn't it be 

`if (arguments[0] instanceof Array`

instead of

`if (arguments[0] instanceof Coordinate`

**Comment by bjornharrtell** [comment]
Yes, it a problem in the Java to JavaScript translation due difficulties determining overload resolution. In general Java arrays are problematic for overload resolutions, since the the type information is not there on the JavaScript side.

But the LinearRing constructor in question is deprecated in favor of GeometryFactory, and I'm not aware of any issues caused by this. Feel free to reopen if you can motivate why this is an issue that needs to be fixed.
