### ISSUE TITLE
Importing Issue? Uncaught TypeError - Vuejs

### ISSUE THREAD

**Issue by qu1ckdry** [bjornharrtell/jsts#315]
Hi,

I'm developing a vue.js app and I'm looking to add your jsts library. I've installed jsts (v1.4.0) via npm and I import it into my code using:
`import * as jsts from 'jsts'`

and this is the function I use it in:

    googleMaps2JTS(boundaries) {
        var coordinates = []
        for (var i = 0; i < boundaries.getLength(); i++) {
        coordinates.push(new jsts.geom.Coordinate(
        boundaries.getAt(i).lat(), boundaries.getAt(i).lng()))
        }
        return coordinates
    },

However when the code executes I get this error:

> Uncaught TypeError: Cannot read property 'Coordinate' of undefined

So I guess it's not importing properly? Any idea what I might be doing wrong?

Thanks!

**Comment by bjornharrtell** [comment]
I think `import jsts from 'jsts'` could work (should try to import the ES5 bundled version) but another option which might be better is to use the ES6 modules directly like for example `import Coordinate from 'jsts/org/locationtech/geom/Coordinate'` but that requires a bundler that understands ES6 modules.

I don't think there is an issue with the npm package, reopen if you can prove otherwise.

**Comment by qu1ckdry** [comment]
Bjorn, thanks for your help. I was able to reference the module directly as you suggegsted

**Comment by RobJmz** [comment]
@qu1ckdry Can you show me your import? I am trying to import exactly the same example (http://www.geocodezip.com/v3_GoogleEx_directions-buffered.html)

But can't seem to make it work, I am using:
import jsts from 'jsts'
import GeometryFactory from 'jsts/org/locationtech/jts/geom/GeometryFactory'
import Coordinate from 'jsts/org/locationtech/jts/geom/Coordinate'

But keep getting errors...
