### ISSUE TITLE
Investigate jsweet as a possible tool for transpilation

### ISSUE THREAD

**Issue by bjornharrtell** [bjornharrtell/jsts#318]
This one seems interesting - http://www.jsweet.org/

For reference, the current transpilation was/is done with my own toolchain at https://github.com/bjornharrtell/java2estree.

**Comment by bjornharrtell** [comment]
Might get into issues with overloading:

https://github.com/cincheo/jsweet/issues/183
https://github.com/cincheo/jsweet/issues/328
https://github.com/cincheo/jsweet/issues/130
https://github.com/cincheo/jsweet/issues/289

**Comment by bjornharrtell** [comment]
Hey @renaudpawlak https://github.com/cincheo/jsweet looks nice. Mabye you'd like to know the results of this investigation.

**Comment by renaudpawlak** [comment]
Hello @bjornharrtell ! Yes, of course, I am interested in seeing the result. Please let me know if you run into problems. There are known issues indeed but globally it works well if you don't rely too much on external libraries and don't push Java too far. You may have to write an extension but I can help in that case... Let me know :)

**Comment by Baehn** [comment]
Hello,

have you been able to use jsts in jsweet? Maybe it is possible to generate a candy for jsweet using the typescript definitions?

**Comment by Baehn** [comment]
Do you think that a manual build of a jsweet candy using onyl jsts is also problematic? If not I could use at least parts of jsts in my project.

**Comment by bjornharrtell** [comment]
I don't know.

**Comment by renaudpawlak** [comment]
I confirm that there are many complicated issues in transpiling Java to plain JavaScript, including overloading (especially when mixed with inheritance). Also, having to deal with modules made it more complicated for JSweet to stay up-to-date with current APIs. However, JSweet does a pretty good job at solving many issues, and when you know how to build a candy manually, it is normally possible to cover and support any kind of interfaces/APIs. All documentation should be avalable [there](http://www.jsweet.org/jsweet-candies/).

Unfortunately, won't be able to investigate either due to lack of time :(

**Comment by bjornharrtell** [comment]
Thanks for that input @renaudpawlak! I hope to eventually get enough time and energy to revisit this. :)
