### ISSUE TITLE
Any chance we could get IndexedPointInAreaLocator exported?

### ISSUE THREAD

**Issue by aickin** [bjornharrtell/jsts#321]
Hey, first, let me just thank you for what an excellent job you've done here in providing enormously useful tools to the world. THANK YOU.

While working on my app, I found that one of the perf pain points was that I am doing thousands of point-in-polygon checks with the same polygon. In looking to see how to fix that, I noticed that IndexedPointInAreaLocator is an object in JTS designed for this exact problem. Further, I saw that there is a port of IndexedPointInAreaLocator in the jsts codebase. Unfortunately, though, the object isn't exported. Is there a reason for that? Would it be possible to export IndexedPointInAreaLocator?

Thanks so much for your time and hard work.

**Comment by bjornharrtell** [comment]
Thanks, happy that this "what if" project has turned out to be quite useful for many including myself. :)

No good reason not to export. The current exports are simply a set of the most common functions that also are all covered by tests.

It's possible to depend on the individual modules and use whatever you like but requires a more or less elaborate build system.

I will leave this open to get it exported at next release. Don't know when I will get to cut a new release though.

**Comment by bjornharrtell** [comment]
Fixed by https://github.com/bjornharrtell/jsts/commit/7607f5cc9dc08edc2a6bdd5fc4d0008891bc491f.
