### ISSUE TITLE
Geometry is missing some methods when used in ES6 modules

### ISSUE THREAD

**Issue by aickin** [bjornharrtell/jsts#323]
Hey there, thanks again for such a great library! I think I've come across a bug, though. If I run this code in an environment that supports webpack & ES6 modules (`create-react-app` in my case), I get an error:

```
import GeometryFactory from "jsts/org/locationtech/jts/geom/GeometryFactory";

const geometryFactory = new GeometryFactory();
geometryFactory.createGeometryCollection([]).union();
```

The error produced is:

```
TypeError: geometryFactory.createGeometryCollection(...).union is not a function
```

and debugging shows that the `geometryFactory` is missing some (but not all) of its methods. Digging further, I found that there's a file called `monkey.js` in the codebase that patches those missing methods onto `Geometry.prototype`, which in turn adds them to `geometryFactory`. Unfortunately, though, `monkey.js` doesn't get imported by itself. 

This code, which explicitly imports `monkey`, produces no error:

```
import GeometryFactory from "jsts/org/locationtech/jts/geom/GeometryFactory";
import "jsts/org/locationtech/jts/monkey.js";

const geometryFactory = new GeometryFactory();
geometryFactory.createGeometryCollection([]).union();
```

So for now I have a workaround, but I think that ideally, jsts should import `monkey` whenever `Geometry` is imported. Thanks!

**Comment by bjornharrtell** [comment]
This is intentional but poorly documented. The reason is that these "shortcut" methods introduce circular dependencies which defeats dead code elimination / tree shaking if you use the ES6 modules directly. The monkey file is, as I see it, a dirty workaround to add these shortcuts methods in the ES5 build to be backwards compatible.

All of the shortcut methods have equivalents as static methods on operations. For instance the union method is the same as using https://github.com/bjornharrtell/jsts/blob/1307dbf2e53cee1670d965abe06d736e4e887946/src/org/locationtech/jts/operation/union/UnionOp.js#L13.

I will leave this open until I get to properly document this deviation from upstream.

**Comment by bjornharrtell** [comment]
Documented at https://github.com/bjornharrtell/jsts/blob/master/README.md#caveats.
