### ISSUE TITLE
Route cross error

### ISSUE THREAD

**Issue by fgarzonhz** [bjornharrtell/jsts#351]
Just like bug: #313
Let me explain, and maybe with the image is more clear:

If you try to do a route with this points: 

[-78.466449, -0.168432]
[-78.465449, -0.168432]
[-78.465449, -0.168632]
[-78.465449, -0.168832]
[-78.465649, -0.168832]
[-78.465649, -0.168432]

The result is as the image1, but if you remove the first coordinate the result is like image2, we expect the result like image3.

we are using:

var geoReader = new jsts.io.GeoJSONReader();
var geoWriter = new jsts.io.GeoJSONWriter();
var geometry = geoReader.read(geoJSON).geometry.buffer(radius);
return geoWriter.write(geometry);
... then we draw in the map.

Thanks for your replay !

Saludos,
Frank

![img1](https://user-images.githubusercontent.com/3596329/43429538-872ad026-9429-11e8-9c4e-25012e134dbd.png)
![img3](https://user-images.githubusercontent.com/3596329/43429539-87474ac6-9429-11e8-8dd6-4f69cf717b38.png)
![img2](https://user-images.githubusercontent.com/3596329/43429540-876223a0-9429-11e8-824d-48ba398bb612.png)

**Comment by bjornharrtell** [comment]
I agree this seems unexpected. Never understood what the problem was in #313.

When time permits I will see if I can reproduce this at upstream.

**Comment by fgarzonhz** [comment]
Thanks bjornharrtell , I continue investigate JSTS where is the problem, I'll let you know if wass possible solve and share the solution.

**Comment by fgarzonhz** [comment]
We are using 1.6.1

**Comment by bjornharrtell** [comment]
I get correct/expected result with the following:

```js
var reader = new jsts.io.WKTReader()
var lineString = reader.read('LINESTRING(-78.466449 -0.168432, -78.465449 -0.168432, -78.465449 -0.168632, -78.465449 -0.168832, -78.465649 -0.168832, -78.465649 -0.168432)')
var buffer = lineString.buffer(0.00005)
var writer = writer = new jsts.io.WKTWriter()
var bufferString = writer.write(buffer)
```

Running the above code results in `bufferString` containing `POLYGON((-78.465699 -0.168482,-78.466449 -0.168482,-78.4664587545161 -0.16848103926402017,-78.46646813417162 -0.16847819397662556,-78.46647677851165 -0.16847357348061512,-78.46648435533906 -0.16846735533905932,-78.46649057348061 -0.16845977851165098,-78.46649519397663 -0.16845113417161825,-78.46649803926401 -0.1684417545161008,-78.466499 -0.168432,-78.46649803926401 -0.1684222454838992,-78.46649519397663 -0.16841286582838175,-78.46649057348061 -0.16840422148834902,-78.46648435533906 -0.16839664466094068,-78.46647677851165 -0.16839042651938488,-78.46646813417162 -0.16838580602337444,-78.4664587545161 -0.16838296073597983,-78.466449 -0.168382,-78.465649 -0.168382,-78.465449 -0.168382,-78.4654392454839 -0.16838296073597983,-78.46542986582838 -0.16838580602337444,-78.46542122148836 -0.16839042651938488,-78.46541364466094 -0.16839664466094068,-78.46540742651939 -0.16840422148834902,-78.46540280602338 -0.16841286582838175,-78.465399960736 -0.1684222454838992,-78.465399 -0.168432,-78.465399 -0.168832,-78.465399960736 -0.1688417545161008,-78.46540280602338 -0.16885113417161826,-78.46540742651939 -0.168859778511651,-78.46541364466094 -0.16886735533905933,-78.46542122148836 -0.16887357348061513,-78.46542986582838 -0.16887819397662557,-78.4654392454839 -0.16888103926402018,-78.465449 -0.168882,-78.465649 -0.168882,-78.4656587545161 -0.16888103926402018,-78.46566813417162 -0.16887819397662557,-78.46567677851165 -0.16887357348061513,-78.46568435533906 -0.16886735533905933,-78.46569057348061 -0.168859778511651,-78.46569519397663 -0.16885113417161826,-78.46569803926401 -0.1688417545161008,-78.465699 -0.168832,-78.465699 -0.168482),(-78.465599 -0.168482,-78.465599 -0.16878200000000002,-78.46549900000001 -0.16878200000000002,-78.46549900000001 -0.168482,-78.465599 -0.168482))` which is a polygon with one hole and is rendered as:

![skarmbild fran 2018-08-01 22-59-46](https://user-images.githubusercontent.com/141030/43548600-b0be4dee-95de-11e8-8a7b-6da6b94127f9.png)

So, the problem was that you for some reason extract the shell of the polygon and throw away the hole. Normally you should not have to mess with the internals of geometry representations.
