### ISSUE TITLE
SyntaxError in Webpack bundle.js Internet Explorer 11

### ISSUE THREAD

**Issue by d-crouch** [bjornharrtell/jsts#368]
I cannot run jsts in my application on Internet Explorer 11. (on Chrome and Firefox it's working)
I bundled my application with webpack.

IE11 Web Console shows: **SyntaxError in bundle.js**.

jsts version: 2.0.2 
@types/jsts version: 0.17.0.

This is my import: `import * as jsts from 'jsts';`

Any suggestions/solutions for this problem?
Thank you.

**Comment by bjornharrtell** [comment]
Since 2.0 the bundled distribution of JSTS does not support IE11 (stated at https://github.com/bjornharrtell/jsts/releases/tag/2.0.0). You can depend on ES6 modules directly or create a custom bundle with IE11 compatibility.

I'm considering reinstating IE11 target in a future release to avoid issues like this but it just doesn't make me very happy to maintain that support so no promises.

**Comment by d-crouch** [comment]
I understand, thank you. And thanks for your quick reply.
