### ISSUE TITLE
.intersects is not a function

### ISSUE THREAD

**Issue by SomasunderAsteroid** [bjornharrtell/jsts#370]
Using latest version, I am getting .intersects is not a function. Initially it was working fine.

**Comment by bjornharrtell** [comment]
I've added "Shortcut methods on Geometry from upstream API are not available (.buffer, .intersects and more) unless using the bundled ES5 version that has these monkey patched in. The shortcut methods have been removed because they cause difficult circular dependencies. You can find the equivalent methods on the appropriate operation class." to the README.md caveats section, I hope that helps.

**Comment by SomasunderAsteroid** [comment]
Thank you so much.
