### ISSUE TITLE
jsts 2.2.3 throws SyntaxError

### ISSUE THREAD

**Issue by Primajin** [bjornharrtell/jsts#405]
When building my [CRA](https://github.com/facebook/create-react-app) with webpack, jsts `2.2.3` throws:

```
./node_modules/jsts/java/lang/Integer.js
SyntaxError: /myPath/node_modules/jsts/java/lang/Integer.js: Unexpected character '#' (2:2)

  1 | export default class Integer {
> 2 |   #value
    |   ^
  3 |   constructor(value) {
  4 |     this.#value = value
  5 |   }
```

I'm also confused a bit about the js file in the java folder - I hope this is not a classic case of Java vs. JavaScript confusion.

![](https://www.seguetech.com/wp-content/uploads/2015/07/segue-blog-java-vs-javascript.png)

`2.2.2` works fine.

**Comment by bjornharrtell** [comment]
You need https://babeljs.io/docs/en/babel-plugin-proposal-class-properties in your build chain. I will try to make that more automatic by including a suitable babel.config.js in the package in the next version.

**Comment by Primajin** [comment]
Alright thanks for the pointer, will try that out!

**Comment by Primajin** [comment]
Hmm so I would have to [eject](https://create-react-app.dev/docs/available-scripts/#npm-run-eject) which is kind of irreversible just to be able to update to your newer version. Otherwise all CRA users (that don't eject) are stuck with this version. This doesn't feel to me like a patch number changer but rather a breaking change... e.g. major version bump...

**Comment by bjornharrtell** [comment]
@Primajin I see, but perhaps it could work with an included babel.config.js? I think it should... if you want to help, I would have use for a minimal reproduction repo.

**Comment by bjornharrtell** [comment]
Looking into it it seems CRA has decided libraries may not use experimental syntax no matter if you want to or not, so a `babel.conf.js` telling it to will not help.

On the case of the `java` folder, JSTS is transpiled from Java, so no, it's not me being confused. :)

I have removed the use of the experimental syntax in the new release 2.3.0. It does have quite a few other changes but I hope it will work for you so that I can avoid having to do a backport to 2.2.x series.

**Comment by Primajin** [comment]
Thanks jsts 2.3.0 builds again in our pipeline!
