### ISSUE TITLE
Substantial portion of Polygon removed after using GeometryPrecisionReducer

### ISSUE THREAD

**Issue by evansiroky** [bjornharrtell/jsts#419]
I recently updated JSTS from 2.1.2 to 2.5.1 and noticed that part of a large polygon is being removed after applying a GeometryPrecisionReducer on the large polygon. I have attached a test case that demonstrates the problem.
See [test.zip](https://github.com/bjornharrtell/jsts/files/5437193/test.zip).

**Comment by dr-jts** [comment]
This is likely due to the use of [buffer](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/precision/GeometryPrecisionReducer.js#L34) as a way to fix the invalid topology of a precision-reduced polygon.

This is now [fixed](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/precision/GeometryPrecisionReducer.java#L138) in JTS by using the new OverlayNG snap-rounding overlay to do precision reduction in a topologically-valid way.  Hopefully this will get ported to JTSTS soon.

**Comment by bjornharrtell** [comment]
@dr-jts I did wonder if this might be an upstream thing.. but then I do wonder why it would be different between 2.1.2 and 2.5.1 (in which I wasn't really expecting the upstream to have any known changes in this behavior)

**Comment by dr-jts** [comment]
>  I do wonder why it would be different between 2.1.2 and 2.5.1 

Yes, I wondered about that as well.  I'm not sure how the JSTS versions map to JTS versions, but there have been a few changes in JTS with might have affected the behaviour of buffer in this area.  This buffer behaviour is fairly non-deterministic, so a small change in some algorithm it uses might cause the output to change.

Bottom line is that this was always a hack, and it's nice that it can be changed to use a more reliable approach (in JTS 1.18).

**Comment by bjornharrtell** [comment]
@dr-jts agreed :)

@evansiroky with this in mind I can't really motivate myself to dig into this case and the current code, sorry.

**Comment by dr-jts** [comment]
Some more info on this.  The reason that part of the polygon is dropped after `buffer(0)` is that it is actually a "figure-8" invalid polygon, with a self-crossing creating two lobes of the polygon.  Buffer(0) generally has the effect of dropping one lobe in this case. 

Unfortunately the fix to precision reduction to use Snap-Rounding won't handle this kind of invalidity either.  Although it does fail with a `TopologyException`, which is an improvement (always better to fail rather than silently corrupt data).

As with most JTS operations, validity is a requirement for precision reduction input.  So handling this case will require making the input valid (which is not yet provided by JTS, but perhaps will be in the future).

**Comment by evansiroky** [comment]
Just to follow up on this, I have been able to manually edit the geometry to change it to a valid MultiPolygon feature. After doing this, I have no issues with reducing precision. I will try to figure out how I ended up with invalid geometry to begin with.
