### ISSUE TITLE
Problems importing jsts

### ISSUE THREAD

**Issue by antonjohanssonse** [bjornharrtell/jsts#420]
Hey , I cannot import and use this package correctly, I'm very confused why. 

I have tried to install different package version but everything returns undefined.

`npm install jsts@2.6.1`

```
import Jsts from 'jsts';
console.log(Jsts); // undefined
```

```
require('jsts');
console.log(new jsts); // undefined
```

```
<script src="https://unpkg.com/jsts@2.6.1/dist/jsts.min.js"></script>
console.log(new jsts); // undefined
```

Any ideas why? @bjornharrtell 

Mvh, Malmö-bo

**Comment by bjornharrtell** [comment]
In the first example casing is wrong, in the other examples you do `new jsts` which doesn't make sense as `jsts` is not a constructor.

Mvh, Malmö-bo i exil.

**Comment by antonjohanssonse** [comment]
casing or naming should not matter then importing a whole package 📦. 

```
npm list jsts
└── jsts@2.6.1 
```

```
import jsts from 'jsts';
console.log(jsts); // still undefined
```

```
<script src="https://unpkg.com/jsts@2.6.1/dist/jsts.min.js"></script>
console.log('WKTReader', new jsts.io.WKTReader()); // Uncaught TypeError: Cannot read property 'io' of undefined
from this example: http://bjornharrtell.github.io/jsts/
```

Using nodejs version **10.16.3**.
Using ReactJS and express.

Any clue why @bjornharrtell nothing works for me? >_<

Mvh

**Comment by bjornharrtell** [comment]
Ah yeah you are right when importing default symbol you choose the name!

Sorry I cannot explain why nothing works for you though.. :P

**Comment by antonjohanssonse** [comment]
I think it has something to do that there is no index.js located in the main folder.. ?

**Comment by bjornharrtell** [comment]
@antonjohanssonse I do not think so. Consider that jsts has a `main` entry in `package.json` at https://github.com/bjornharrtell/jsts/blob/489d80acd0d07052cdeb80a5e848b94806b315d2/package.json#L36. I suspect you are having a react/webpack configuration issue which I cannot help you with as I do not use react/webpack myself as I prefer other more pleasant frontend technologies.

Probably unrelated to the issue but I would recommend importing individual modules instead of the main dist entry point as described at https://github.com/bjornharrtell/jsts#es6-modules-use. Both that example and the fact that all test cases for jsts run in node is proving that it should run fine in node though and you'll have to provide something more sustantial and reproducible if you want help.

**Comment by antonjohanssonse** [comment]
Okey , ye I tried to withdraw only the necessary modules from your package but got too frustrated, and then found this http://turfjs.org/docs/#union which worked perfectly for me for now.

thank you alot for quick answers <3 

kind regards

**Comment by bjornharrtell** [comment]
Hey turf uses JSTS, sometimes 😝

(https://github.com/Turfjs/turf/blob/c952c44a25cb9ceba82f140b2b0407d8484afac4/packages/turf-buffer/package.json#L71)
