### ISSUE TITLE
2.7.0: Imports broken

### ISSUE THREAD

**Issue by ablakey** [bjornharrtell/jsts#437]
Npm automatically did a minor bump to 2.7.0 and now my imports are broken:

`import * as jsts from "jsts";`

No-longer works:

```
WARNING in ./src/lib/gis/jsts.ts 98:24-61
export 'operation' (imported as 'jsts') was not found in 'jsts' (module has no exports)
```

I'll investigate further, but wanted to raise this either way because it's either an unintended change, or one that probably deserves a major version increment?

Thank you, as always, for maintaining this project.

**Comment by bjornharrtell** [comment]
Thanks for the heads up, and yeah it's not intended. I think it is because I've tried to move away from esm which is abandoned and made the package type into module, here: https://github.com/bjornharrtell/jsts/blob/cc954e3faac54c550e30919fb2a45f6d9e2ee15c/package.json#L37.

I also have main and module fields in package.json pointing to bundled entry points, with at least the main one (dist/jsts.min.js) not being a real module.. and I didn't even build and include dist/jsts.es6.min.js.

I will have to read up on how to properly setup entry point for a package with type module... I do not use the entry point myself because I think it is better to import individual modules and that seems to be working fine.

I will consider reissuing 2.6.2 + regression fix as 2.7.1 and make a major bump for this stuff.

**Comment by bjornharrtell** [comment]
I've issued 2.7.1 which should hopefully be non breaking and will try to see to it that 3.0.0 works with the bundle entry point (or possible remove them entirely..)

**Comment by ablakey** [comment]
Thanks!  2.7.1 works again with the original import format.

I'm not sure if importing all is a good idea or not. I assumed webpack would tree shake, but I haven't actually proven that out or experimented with how well JSTS shrinks down when only important needed functions.

**Comment by bjornharrtell** [comment]
@ablakey in general three shaking isn't very effective on JSTS because the internal dependencies are far reaching, but I do believe importing individual classes can save a bit.
