### ISSUE TITLE
IllegalStateException is not defined

### ISSUE THREAD

**Issue by quachc** [bjornharrtell/jsts#469]
We see this reference error being thrown from: `LineSegment#pointAlongOffset` (jsts/src/org/locationtech/jts/geom/LineSegment.js:202:22)

**Comment by bjornharrtell** [comment]
Can you supply a failing test case?

**Comment by quachc** [comment]
See https://github.com/quachc/jsts/blob/master/test/manual/geom/LineSegment.js

**Comment by bjornharrtell** [comment]
@quachc IllegalStateException was not correctly implemented, fixed by https://github.com/bjornharrtell/jsts/commit/5f866f91cd924b709361e1b107fa8f298f5e445a.

However, your test case is with input that is intended to fail which is the reason that it wants to throw IllegalStateException. I'm pretty sure it works in latest release with valid data (i.e segment cannot be zero length).
